### ISSUE TITLE
Data is not streamed from Kafka to Cassandra

### ISSUE THREAD

**Issue by arrismo** [airscholar/e2e-data-engineering#8]
The Keyspace and Table is created but the Cassandra database is empty. 

Using Cassandra 4.1.7
Spark 3.4.1
Scala 2.12.17

Command to submit a job:
spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1,com.datastax.spark:spark-cassandra-connector_2.12:3.4.1, \
--master spark://spark-master:7077 \
spark_stream.py

**Comment by kushagr538** [comment]
Hi I am facing the same issue. How did you resolve it?

**Comment by arrismo** [comment]
I wasn't able to fix it, I just worked on another project.
